// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQr6pNYbPUf8p3j_URW5BqnO2NoefWZ0',
    appId: '1:1090501322083:web:987b140e4fbf2261175f56',
    messagingSenderId: '1090501322083',
    projectId: 'projectsync-f9b50',
    authDomain: 'projectsync-f9b50.firebaseapp.com',
    storageBucket: 'projectsync-f9b50.appspot.com',
    measurementId: 'G-E73KFD769R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchec5LkDIvyveG0M-QjWIt7ny_PZEg5Q',
    appId: '1:1090501322083:android:221b2cce16f9ff59175f56',
    messagingSenderId: '1090501322083',
    projectId: 'projectsync-f9b50',
    storageBucket: 'projectsync-f9b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1e5AX5JMzr0-SRT0aRQXzJQfxz_0d6U',
    appId: '1:1090501322083:ios:c148c38b3f8aaf95175f56',
    messagingSenderId: '1090501322083',
    projectId: 'projectsync-f9b50',
    storageBucket: 'projectsync-f9b50.appspot.com',
    iosBundleId: 'com.example.projectSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1e5AX5JMzr0-SRT0aRQXzJQfxz_0d6U',
    appId: '1:1090501322083:ios:e31f36e0a2dc75c4175f56',
    messagingSenderId: '1090501322083',
    projectId: 'projectsync-f9b50',
    storageBucket: 'projectsync-f9b50.appspot.com',
    iosBundleId: 'com.example.projectSync.RunnerTests',
  );
}
